services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://P3_owner:npg_DGTw7x4dPcWt@ep-quiet-snowflake-ac1cc33r-pooler.sa-east-1.aws.neon.tech/P3?sslmode=require&channel_binding=require"
      PORT: 3000
      NODE_ENV: production
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    command: ["node", "dist/index.js"]
